### ISSUE TITLE
Update to 0.9.5?

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.github.babluboy.bookworm#1]
Looks like there's a newer and more awesome release upstream. 

https://github.com/babluboy/bookworm/releases 

@BharatKalluri @babluboy do you plan on doing an update here?

**Comment by babluboy** [comment]
@nedrichards...yes definitely want to update the flathub for the latest version of bookworm...I intentionally did not push the change to flathub as I was leaving on vacation and also was trying to see if there are any gaps reported due to the change in DB structure introduced in bookworm v9.5 ....

So far the release looks good but not sure how I can release to flathub using my phone...maybe this has to wait until I'm back home on the 6th...

Let me know if there is anything I can do online on an iPhone....

**Comment by nedrichards** [comment]
Interesting point! I'm not sure if the github editor works on a phone, but if it does you could technically use that and do a test build as a Pull Request. However, if the only thing to change in the release is the URL and the sha256sum then I'm happy to do that stuff myself and get you to review the pull request, which you can do from your phone.

**Comment by babluboy** [comment]
I have merged your PR...hopefully it builds fine ...let me know if you see any issues....interesting fact: I merged the PR from a flight before putting my mobile into flight mode !!...never thought I can build software on this situation....😀
