### ISSUE TITLE
Needs to expose higher res icon

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.github.babluboy.bookworm#3]
It looks like we're not quite correctly exposing high res icons in the appdata - which means the Bookworm icon isn't showing up in the [beta flathub apps page](https://beta.flathub.org/apps) (which looks up data live)

**Comment by babluboy** [comment]
@nedrichards Thanks for raising this. I remember that in the last release I had the binary name in the appdata xml as `<binary>bookworm</binary>` which I have since corrected to `<binary>com.github.babluboy.bookworm</binary>`

Do you feel the above is the reason for the issue. Apart from that the desktop file mentions the correct icon name i.e. `Icon=com.github.babluboy.bookworm`. Will be good to know how flathub picks up the live data

**Comment by nedrichards** [comment]
The Flathub web app gets the data from the appstream - I believe it's looking for 64x64px and 128x128px icons right now under the usual path `hicolor` etc.

**Comment by babluboy** [comment]
Thanks for the pointer. I checked and found that the dimensions of all the icons is 64x64 instead of the the correct ones. Maybe this is causing the issue as the 128x128 icon is actually 64x64.
Will correct this in the next release and see if this resolves the issue.

**Comment by nedrichards** [comment]
That could well be an issue!

**Comment by babluboy** [comment]
Just pushed changes to master to correct the icon sizes. Hopefully this issue should be fixed now. Guess we need to wait for the next GH Release for bookworm to test if this issue is resolved

**Comment by babluboy** [comment]
release 1.0.0 of Bookworm has proper icons for all different sizes.
closing this issue as I can already see the bookworm icon on [beta flathub apps page](https://beta.flathub.org/apps)
